"""removed lessoon_id from teacher

Revision ID: 1e53edde8a51
Revises: ff0d0fded14c
Create Date: 2024-04-02 18:02:39.484993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e53edde8a51'
down_revision: Union[str, None] = 'ff0d0fded14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'lesson')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('lesson', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
