"""lessons time is now time instead of datetime

Revision ID: 57ec6f6e68ce
Revises: 1e53edde8a51
Create Date: 2024-04-02 18:44:44.686610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57ec6f6e68ce'
down_revision: Union[str, None] = '1e53edde8a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson', 'start',
               existing_type=postgresql.TIMESTAMP(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson', 'start',
               existing_type=postgresql.TIME(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
