"""first valueable product tables

Revision ID: c4a4745d8b75
Revises: 
Create Date: 2024-04-02 19:42:03.533838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4a4745d8b75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet', sa.String(), nullable=True),
    sa.Column('pavilion', postgresql.ENUM('NEW', 'MAIN', 'LAB', 'SPORT_OLD', 'SPORT_NEW', 'STADIUM', name='pavilion'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('patronymic', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_day', postgresql.ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='dayofaweek'), nullable=False),
    sa.Column('start', postgresql.TIME(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('type', postgresql.ENUM('LECTURE', 'PRACTICE', 'LABORATORY', name='lessontype'), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    op.drop_table('teacher')
    op.drop_table('place')
    # ### end Alembic commands ###
