name: Build and Push on dockerhub

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  bash_get_version:
    name: Get project version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.evaluation.outputs.version }}
    steps:
      - name: Checkout pyproject.toml
        uses: actions/checkout@v4
        with:
          sparse-checkout: pyproject.toml
          sparse-checkout-cone-mode: false
      - name: Evaluate version from file
        id: evaluation
        run: echo "version=$(cat pyproject.toml | awk 'FNR == 3 {print $3}' | tr -d '"')" >> "$GITHUB_OUTPUT"
  
  docker_build_push:
    name: Push Docker image to Docker Hub
    environment: build
    runs-on: ubuntu-latest
    needs: bash_get_version
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}
    steps:
      - name: Print version
        run: echo ${{ needs.bash_get_version.outputs.version }}
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ needs.bash_get_version.outputs.version }}
            ${{ env.DOCKER_REPO }}:latest
  
  ssh_deploy:
    environment: deploy
    runs-on: ubuntu-latest
    needs: [bash_get_version, docker_build_push]
    env:
      GITHUB_REPO: ${{ github.event.repository.name }}
      DOCKER_REPO: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}
      DOCKER_TAG: ${{ needs.bash_get_version.outputs.version }}
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          port: ${{ secrets.SSH_PORT }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          debug: true
          script: |
            docker pull ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }} *> $null && ^
            docker stop ${{ env.GITHUB_REPO }} *> $null && ^
            docker remove ${{ env.GITHUB_REPO }} *> $null && ^
            docker run -d -p 8118:8118 --name ${{ env.GITHUB_REPO }} ${{ env.DOCKER_REPO }}:${{ env.DOCKER_TAG }}
