name: Pytest with Poetry on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      - name: Install dependencies with Poetry
        run: poetry install
      - name: Run pytest
        run: poetry run pytest --junit-xml=test-results.xml
      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          fail-on-empty: true
          title: Test Results